# vim: ft=tmux

# mouse support
set -g mouse on

# vim stype copy mode
setw -g mode-keys vi

# reload config file (change file location to your the tmux.conf you want to use)
bind C-r source-file ~/.config/tmux/tmux.conf \; display "Config reloaded"

# split panes using | and -
bind | split-window -h
bind - split-window -v
unbind '"'
unbind %

# join-pane (prefix+! break-pane)
bind j choose-window 'join-pane -h -s "%%"'
bind J choose-window 'join-pane -s "%%"'

# switch panes using Alt-arrow without prefix
bind -n M-Left select-pane -L
bind -n M-Right select-pane -R
bind -n M-Up select-pane -U
bind -n M-Down select-pane -D
# also vim-style hjkl navigation
bind -n M-h select-pane -L
bind -n M-j select-pane -D
bind -n M-k select-pane -U
bind -n M-l select-pane -R

