# vim: ft=tmux

# mouse support
set -g mouse on

# vim stype copy mode
setw -g mode-keys vi

# reload config file (change file location to your the tmux.conf you want to use)
bind C-r source-file ~/.config/tmux/tmux.conf \; display "Config reloaded"

# split panes using | and -
bind | split-window -h
bind - split-window -v
unbind '"'
unbind %

# join-pane (prefix+! break-pane)
# join to window
bind j choose-window 'join-pane -h -t "%%"'
bind J choose-window 'join-pane -t "%%"'
# grab from window
bind g choose-window 'join-pane -h -s "%%"'
bind G choose-window 'join-pane -s "%%"'

# swap windows
bind < swap-window -t -1
bind > swap-window -t +1

# toggle status-line
bind _ set-option status

# clear window title
bind M-, setw automatic-rename on

# toggle sync mode (broadcast keyboard input to all panes in a windows)
bind M-s setw synchronize-panes

# switch panes using Alt-arrow without prefix
bind -n M-Left select-pane -L
bind -n M-Right select-pane -R
bind -n M-Up select-pane -U
bind -n M-Down select-pane -D
# also vim-style hjkl navigation
bind -n M-h select-pane -L
bind -n M-j select-pane -D
bind -n M-k select-pane -U
bind -n M-l select-pane -R

# swap panes using Alt-shift-arrow
bind -n M-S-Left swap-pane -t '{left-of}'
bind -n M-S-Right swap-pane -t '{right-of}'
bind -n M-S-Up swap-pane -t '{up-of}'
bind -n M-S-Down swap-pane -t '{down-of}'
# also vim-style hjkl navigation
bind -n M-H swap-pane -t '{left-of}'
bind -n M-J swap-pane -t '{down-of}'
bind -n M-K swap-pane -t '{up-of}'
bind -n M-L swap-pane -t '{right-of}'

# move pane focus cyclically
bind -n M-o select-pane -t :.+
# move pane cyclically
bind -n M-O rotate-window

# zoom pane
bind -n M-z resize-pane -Z

# change windows focus
bind -n M-1 select-window -t :=1
bind -n M-2 select-window -t :=2
bind -n M-3 select-window -t :=3
bind -n M-4 select-window -t :=4
bind -n M-5 select-window -t :=5
bind -n M-6 select-window -t :=6
bind -n M-7 select-window -t :=7
bind -n M-8 select-window -t :=8
bind -n M-9 select-window -t :=9
bind -n M-0 select-window -t :=10

# select-window
bind 1  select-window -t :=1
bind 2  select-window -t :=2
bind 3  select-window -t :=2
bind 4  select-window -t :=4
bind 5  select-window -t :=5
bind 6  select-window -t :=6
bind 7  select-window -t :=7
bind 8  select-window -t :=8
bind 9  select-window -t :=9
bind 0  select-window -t :=10

