# vim: ft=tmux

set -g @catppuccin_flavor 'mocha'
# set -g @catppuccin_window_default_text " #W"
# better windws title: pane title if no windows title set, windows title: pane title elsewise
set -g @catppuccin_window_current_text " #{?automatic-rename,#T,#W: #T}"
set -g @catppuccin_window_text " #{?automatic-rename,#T,#W: #T}"

# color config for tmux_mode_indicator
# style values for prefix prompt
set -g @mode_indicator_prefix_mode_style 'bg=#{@thm_blue},fg=#{@thm_crust}'
# style values for copy prompt
set -g @mode_indicator_copy_mode_style 'bg=#{@thm_yellow},fg=#{@thm_crust}'
# style values for sync prompt
set -g @mode_indicator_sync_mode_style 'bg=#{@thm_red},fg=#{@thm_crust}'
# style values for empty prompt
set -g @mode_indicator_empty_mode_style 'bg=#{@thm_green},fg=#{@thm_crust}'

# Make the status line more pleasant.
set -g status-left ''
set -ag status-left "#{tmux_mode_indicator} "
set -g status-right ''
set -ag status-right '#(LANG=en_US.UTF-8 date "+%%a %%-d %%b %%H:%%M") '
set -ag status-right '#[fg=#{@thm_crust},bg=#{@thm_peach}]#{?window_zoomed_flag, 󰊓 ,}'
set -ag status-right '#[default]#{?window_zoomed_flag, ,}'
set -ag status-right '#[fg=#{@thm_crust},bg=#{@thm_sapphire}] #S #[default]'

run ~/.config/tmux/plugins/catppuccin/tmux/catppuccin.tmux

