# vim: ft=tmux

set -g @catppuccin_flavor 'mocha'

# Make the status line more pleasant.
set -g status-left ""
set -g status-right '#[fg=#{@thm_crust},bg=#{@thm_teal}]  #S '

run ~/.config/tmux/plugins/catppuccin/tmux/catppuccin.tmux

