# vim: ft=tmux

set -g @catppuccin_flavor 'mocha'

# color config for tmux_mode_indicator
# style values for prefix prompt
set -g @mode_indicator_prefix_mode_style 'bg=#{@thm_blue},fg=#{@thm_crust}'
# style values for copy prompt
set -g @mode_indicator_copy_mode_style 'bg=#{@thm_yellow},fg=#{@thm_crust}'
# style values for sync prompt
set -g @mode_indicator_sync_mode_style 'bg=#{@thm_red},fg=#{@thm_crust}'
# style values for empty prompt
set -g @mode_indicator_empty_mode_style 'bg=#{@thm_green},fg=#{@thm_crust}'

# Make the status line more pleasant.
set -g status-left "#{tmux_mode_indicator} "
set -g status-right '#(LANG=en_US.UTF-8 date "+%%a %%-d %%b %%H:%%M") #[fg=#{@thm_crust},bg=#{@thm_sapphire}] #S #[default]'

run ~/.config/tmux/plugins/catppuccin/tmux/catppuccin.tmux

