# vim: ft=tmux

# misc
source-file ~/.config/tmux/misc.conf

# keybindings
source-file ~/.config/tmux/keybindings.conf

# local overrides
source-file ~/.config/tmux/local.conf

# themes
source-file ~/.config/tmux/theme.conf

# plugins (keep this at buttom)
source-file ~/.config/tmux/tpm.conf

