# vim: ft=tmux

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'jaclu/tmux-menus'
set -g @plugin 'MunifTanjim/tmux-mode-indicator'
set -g @plugin 'rickstaa/tmux-notify'
set -g @plugin 'tmux-plugins/tmux-yank'

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.config/tmux/plugins/tpm/tpm'

