[ids]
*

[main]
# leftmeta+leftshift+f23 = overload(control, esc)
leftmeta+leftshift+f23 = rightcontrol
leftalt = leftcontrol
leftcontrol = leftalt
capslock = overload(caps_layer, C-S-2)
# layer(control)
# f23+leftshift+leftmeta = layer(control)
#
[caps_layer]
c = capslock
# nav
h = left
j = down
k = up
l = right
y = home
u = pagedown
i = pageup
o = end
e = esc
